services:
  # API Gateway
  tms.apigateway:
    image: ${DOCKER_REGISTRY-}tmsapigateway
    build:
      context: .
      dockerfile: src/TMS.ApiGateway/Dockerfile
    container_name: tms-gateway
    environment:
      - JWT_KEY=${JWT_KEY}
    ports:
      - "8080"
      - "8081"
    depends_on:
      - tms.authservice
      - tms.taskservice
      - tms.filestorageservice
      - tms.notificationservice

  # AuthService
  tms.authservice:
    image: ${DOCKER_REGISTRY-}tmsauthservice
    build:
      context: .
      dockerfile: src/TMS.AuthService/Dockerfile
    container_name: tms-auth-service
    environment:
      - POSTGRES_USER=${AUTH_POSTGRES_USER}
      - POSTGRES_PASSWORD=${AUTH_POSTGRES_PASSWORD}
      - POSTGRES_DB=${AUTH_POSTGRES_DB}
      - POSTGRES_HOST=tms-auth-db
      - JWT_KEY=${JWT_KEY}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - REDIS_HOST=tms-auth-redis
      - REDIS_PORT=${AUTH_REDIS_PORT}
      - REDIS_PASSWORD=${AUTH_REDIS_PASSWORD}
    depends_on:
      - tms.auth-db
      - tms.auth-redis 


  tms.auth-db:
    image: postgres:13
    container_name: tms-auth-db
    environment:
      - POSTGRES_USER=${AUTH_POSTGRES_USER}
      - POSTGRES_PASSWORD=${AUTH_POSTGRES_PASSWORD}
      - POSTGRES_DB=${AUTH_POSTGRES_DB}
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    

  tms.auth-redis:
    image: redis:6
    container_name: tms-auth-redis
    volumes:
        - auth-redis-data:/data
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${AUTH_REDIS_PASSWORD}"]


  # TaskService
  tms.taskservice:
    image: ${DOCKER_REGISTRY-}tmstaskservice
    build:
      context: .
      dockerfile: src/TMS.TaskService/Dockerfile
    container_name: tms-task-service
    environment:
      - POSTGRES_USER=${TASK_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TASK_POSTGRES_PASSWORD}
      - POSTGRES_DB=${TASK_POSTGRES_DB}
      - POSTGRES_HOST=tms-task-db
      - JWT_KEY=${JWT_KEY}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - FILES_HOST=tms-file-storage-service
    depends_on:
      - tms.task-db
      - tms.authservice
      - tms.notificationservice


  tms.task-db:
    image: postgres:13
    container_name: tms-task-db
    environment:
      - POSTGRES_USER=${TASK_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TASK_POSTGRES_PASSWORD}
      - POSTGRES_DB=${TASK_POSTGRES_DB}
    volumes:
      - task-db-data:/var/lib/postgresql/data

  # FileStorageService
  tms.filestorageservice:
    image: ${DOCKER_REGISTRY-}tmsfilestorageservice
    build:
      context: .
      dockerfile: src/TMS.FileStorageService/Dockerfile
    container_name: tms-file-storage-service
    environment:
      - POSTGRES_USER=${FILE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${FILE_POSTGRES_PASSWORD}
      - POSTGRES_DB=${FILE_POSTGRES_DB}
      - POSTGRES_HOST=tms-files-db
      - BASE_FILES_PATH=${BASE_FILES_PATH}
    depends_on:
      - tms.files-db


  tms.files-db:
    image: postgres:13
    container_name: tms-files-db
    environment:
      - POSTGRES_USER=${FILE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${FILE_POSTGRES_PASSWORD}
      - POSTGRES_DB=${FILE_POSTGRES_DB}
    volumes:
      - files-db-data:/var/lib/postgresql/data

  # NotificationService
  tms.notificationservice:
    image: ${DOCKER_REGISTRY-}tmsnotificationservice
    build:
      context: .
      dockerfile: src/TMS.NotificationService/Dockerfile
    container_name: tms-notification-service
    environment:
      - POSTGRES_USER=${NOTIFY_POSTGRES_USER}
      - POSTGRES_PASSWORD=${NOTIFY_POSTGRES_PASSWORD}
      - POSTGRES_DB=${NOTIFY_POSTGRES_DB}
      - POSTGRES_HOST=tms-notify-db
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - BASE_EVENTS_PATH=${BASE_EVENTS_PATH}
    depends_on:
      - tms.authservice
      - tms.notify-db
      - tms.rabbitmq

  tms.notify-db:
    image: postgres:13
    container_name: tms-notify-db
    environment:
      - POSTGRES_USER=${NOTIFY_POSTGRES_USER}
      - POSTGRES_PASSWORD=${NOTIFY_POSTGRES_PASSWORD}
      - POSTGRES_DB=${NOTIFY_POSTGRES_DB}
    volumes:
      - notify-db-data:/var/lib/postgresql/data
 
  tms.rabbitmq:
    image: rabbitmq:3-management
    container_name: tms-rabbitmq
    ports:
      - "5672:5672"   # Порт для приложений
      - "15672:15672" # Порт веб‑интерфейса (UI)
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
 

volumes:
  auth-db-data:
  auth-redis-data:
  task-db-data:
  files-db-data:
  notify-db-data:
  rabbitmq_data:

