services:
  # API Gateway
  tms.apigateway:
    image: ${DOCKER_REGISTRY-}tmsapigateway
    build:
      context: .
      dockerfile: src/TMS.ApiGateway/Dockerfile
    container_name: tms-gateway
    env_file:
      - .env
    ports:
      - "8080"
      - "8081"
    depends_on:
      - tms.authservice
      - tms.taskservice
      - tms.filestorageservice
      - tms.notificationservice

  # AuthService
  tms.authservice:
    image: ${DOCKER_REGISTRY-}tmsauthservice
    build:
      context: .
      dockerfile: src/TMS.AuthService/Dockerfile
    container_name: tms-auth-service
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${AUTH_POSTGRES_USER}
      - POSTGRES_PASSWORD=${AUTH_POSTGRES_PASSWORD}
      - POSTGRES_DB=auth_db
      - POSTGRES_HOST=tms-auth-db
      - REDIS_HOST=tms-auth-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${AUTH_REDIS_PASSWORD}
    depends_on:
      - tms.auth-db
      - tms.auth-redis 


  tms.auth-db:
    image: postgres:13
    container_name: tms-auth-db
    environment:
      - POSTGRES_USER=${AUTH_POSTGRES_USER}
      - POSTGRES_PASSWORD=${AUTH_POSTGRES_PASSWORD}
      - POSTGRES_DB=tms-auth-db
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    

  tms.auth-redis:
    image: redis:6
    container_name: tms-auth-redis
    volumes:
        - auth-redis-data:/data
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${AUTH_REDIS_PASSWORD}"]


  # TaskService
  tms.taskservice:
    image: ${DOCKER_REGISTRY-}tmstaskservice
    build:
      context: .
      dockerfile: src/TMS.TaskService/Dockerfile
    container_name: tms-task-service
    env_file:
      - .env
    volumes:
      - file_storage:/app/files
    environment:
      - POSTGRES_USER=${TASK_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TASK_POSTGRES_PASSWORD}
      - POSTGRES_DB=task_db
      - POSTGRES_HOST=tms-task-db
      - RABBITMQ_HOST=tms-rabbitmq
      - FILES_HOST=tms-file-storage-service
    depends_on:
      - tms.task-db
      - tms.authservice
      - tms.notificationservice


  tms.task-db:
    image: postgres:13
    container_name: tms-task-db
    environment:
      - POSTGRES_USER=${TASK_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TASK_POSTGRES_PASSWORD}
      - POSTGRES_DB=tms-task-db
    volumes:
      - task-db-data:/var/lib/postgresql/data

  # FileStorageService
  tms.filestorageservice:
    image: ${DOCKER_REGISTRY-}tmsfilestorageservice
    build:
      context: .
      dockerfile: src/TMS.FileStorageService/Dockerfile
    container_name: tms-file-storage-service
    env_file:
      - .env
    user: "root"
    environment:
      - POSTGRES_USER=${FILE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${FILE_POSTGRES_PASSWORD}
      - POSTGRES_DB=tms-files-db
      - POSTGRES_HOST=tms-files-db
    depends_on:
      - tms.files-db


  tms.files-db:
    image: postgres:13
    container_name: tms-files-db
    environment:
      - POSTGRES_USER=${FILE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${FILE_POSTGRES_PASSWORD}
      - POSTGRES_DB=tms-files-db
    volumes:
      - files-db-data:/var/lib/postgresql/data

  # NotificationService
  tms.notificationservice:
    image: ${DOCKER_REGISTRY-}tmsnotificationservice
    build:
      context: .
      dockerfile: src/TMS.NotificationService/Dockerfile
    container_name: tms-notification-service
    env_file:
      - .env
    user: "root"
    volumes:
      - email_storage:/app/emails/events
    environment:
      - POSTGRES_USER=${NOTIFY_POSTGRES_USER}
      - POSTGRES_PASSWORD=${NOTIFY_POSTGRES_PASSWORD}
      - POSTGRES_DB=tms-notify-db
      - POSTGRES_HOST=tms-notify-db
      - RABBITMQ_HOST=tms-rabbitmq
    depends_on:
      - tms.authservice
      - tms.notify-db
      - tms.rabbitmq

  tms.notify-db:
    image: postgres:13
    container_name: tms-notify-db
    environment:
      - POSTGRES_USER=${NOTIFY_POSTGRES_USER}
      - POSTGRES_PASSWORD=${NOTIFY_POSTGRES_PASSWORD}
      - POSTGRES_DB=tms-notify-db
    volumes:
      - notify-db-data:/var/lib/postgresql/data
 
  tms.rabbitmq:
    image: rabbitmq:3-management
    container_name: tms-rabbitmq
    ports:
      - "5672:5672"   # Порт для приложений
      - "15672:15672" # Порт веб‑интерфейса (UI)
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
 

volumes:
  auth-db-data:
  auth-redis-data:
  task-db-data:
  files-db-data:
  notify-db-data:
  rabbitmq_data:
  file_storage:
  email_storage:

